config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get 'home/index'
  # get 'contacts' => 'contacts#new'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="mb-5">Edit Article</h1>

  <%= form_for :article, url: article_path(@article), method: :put, :html => { :class => "form-horizontal-center" } do |f| %>
    <div class="form-group">
      <%= f.label :title, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_field :title, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :text, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_area :text, :class => "form-control" %>
      </div>
    </div>

    <%= f.submit :class => "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1 class="mb-5">List of articles:</h1>

  <% @articles.each do |article| %>
  <div class="container mt-5">
    <h4 class="text-muted mb-3">
      <%= article.title %>
    </h4>
    <div class="p-2 border rounded">
      <%= article.text %>
    </div>
    <div class="container mt-4">
      <div class="row">
        <%= link_to 'Show', article_path(article), :class => "btn btn-primary btn-sm mr-2" %>
        <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-primary btn-sm mr-2" %>
        <%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-sm" %>
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="mb-5">New Article</h1>

  <%= form_for :article, url: articles_path, :html => { :class => "form-horizontal-center" } do |f| %>
    <div class="form-group">
      <%= f.label :title, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_field :title, :class => "form-control", :autofocus => true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :text, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_area :text, :class => "form-control" %>
      </div>
    </div>

    <%= f.submit :class => "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %></h1>

  <p>
    <%= @article.text %>
  </p>

  <div class="container p-0 mt-5 mb-5 border rounded p-3">
    <h5 class="text-muted mt-3 mb-3">
      Comments:
    </h5>
    <% @article.comments.each do |comment| %>
      <p class="mt-4">
        <%= comment.body %>
      </p>
      <small class="text-muted mr-2">
        Author:
      </small>
      <small>
        <%= comment.author %>
      </small>
      <hr>
    <% end %>
  </div>

  <p class="text-muted">
    Add comment
  </p>

  <%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="form-group">
    <%= f.label :author, :class => "form-group" %>
    <div class="col-md-8">
      <%= f.text_field :author, :class => "form-control", :autofocus => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, :class => "form-group" %>
    <div class="col-md-8">
      <%= f.text_area :body, :class => "form-control" %>
    </div>
  </div>

  <%= f.submit :class => "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Thanks!</h1>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h1 class="mb-5"><%= t('contacts.contact_us') %></h1>

  <%= form_for :contact, url: contacts_path, :html => {:class => "form-horizontal center"} do |f| %>
    <% if @contact && @contact.errors.any? %>
      <p>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <div class="form-group">
      <%= f.label :email, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_field :email, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :message, :class => "form-group" %>
      <div class="col-md-8">
        <%= f.text_area :message, :class => "form-control" %>
      </div>
    </div>

      <%= f.submit 'Send message', :class => "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1>Blog_2</h1>
  <p class="text-muted">Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
        <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="text-muted">
        <% if user_signed_in? %>
          Hello <%= current_user.username %>
          <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn-link text-decoration-none pl-0" %>
        <% else %>
          <%= button_to "Sign in", new_user_session_path, :class => "btn btn-link text-decoration-none pl-0" %>
        <% end %>
      </div>
    </div>

    <div class="container">
        <p class="notice text-muted"><%= notice %></p>
        <p class="alert text-muted"><%= alert %></p>
    </div>


    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1 class="mb-5">About us</h1>

  <p class="text-muted">
    The text The text The text The text
    The text The text The text
  </p>
</div>

app/views/pages/terms.html.erb
<div class="container">
  <h1 class="mb-5">Terms of Service</h1>

  <p class="text-muted">
    The small text, go go go go go go go go go go
  </p>
</div>